In [8]:
#1.List 5 daily actions you perform on apps like Instagram, Zomato, 
# or Flipkart, and for each, identify whether the data generated is numerical or categorical.
import pandas as pd 

data={"action":["Like a post on Instagram","Search for Pizza on Zomato","Order food on Zomato",
                "Choose payment method on Flipkart","Select Product Color on Flipkart"],
      "data generated":["Number of Likes:1000","Search Keyword:science","Order Amount:10000","Payment Method:credit card","Product Color:blue"],  
      "data type":["Numerical","Categorical","Numerical", "Categorical", "Categorical"]
        }
df=pd.DataFrame(data)
#print(df)
df

                              action              data generated    data type
0           Like a post on Instagram        Number of Likes:1000    Numerical
1         Search for Pizza on Zomato      Search Keyword:science  Categorical
2               Order food on Zomato          Order Amount:10000    Numerical
3  Choose payment method on Flipkart  Payment Method:credit card  Categorical
4   Select Product Color on Flipkart          Product Color:blue  Categorical

In [1]:
#2.Given this sample data from a music app: ['Pop', 'Rock', 'Jazz', 'Hip-Hop', 'Pop', 'Rock', 'Jazz', 'Pop'], 
# classify the type of data and explain your reasoning in 2-3 lines.
import pandas as np
import pandas as pd

sample_data=np.array(['Pop', 'Rock', 'Jazz', 'Hip-Hop', 'Pop', 'Rock', 'Jazz', 'Pop'])
print("data type is:",sample_data.dtype)

sample=pd.Series(sample_data)
print("data type is:",sample.dtypes)

data=pd.DataFrame(sample)
print("data type is:",data.dtypes)

print("classification: Categorical Data")
print("reason: The values represent  labels(string), not numbers")
print("they cannot be measured or used in mathematical calculations")

data type is: string
data type is: string
data type is: 0    string[python]
dtype: object
classification: Categorical Data
reason: The values represent  labels(string), not numbers
they cannot be measured or used in mathematical calculations

In [2]:
#3.Pick any one feature from an app you use (such as the number of likes on an Instagram post, or 
# the rating of a restaurant on Zomato) and describe how statistics could help improve that feature for users.
import pandas as pd

ratings = pd.Series([5, 4, 3, 5, 2, 4, 5, 3])

print("average Rating:", ratings.mean())
print("median Rating:", ratings.median())
print("most Common Rating:", ratings.mode()[0])

print("mean shows the average rating of the restaurant")
print("median shows the middle rating given by customers")
print("mode shows the rating that customers give most")

average Rating: 3.875
median Rating: 4.0
most Common Rating: 5
mean shows the average rating of the restaurant
median shows the middle rating given by customers
mode shows the rating that customers give most

In [4]:
#4.Suppose you are building a new playlist recommendation feature for a Spotify-like app. List 3 basic statistical terms (such as mean, median, mode, variance, etc.) 
# that would be useful in analyzing user listening data, and explain each with a one-line example.
import pandas as pd
import numpy as np

data={"song_name":["Kesariya","Tere Sang Yaara","Tum Hi Ho","Channa Mereya","Dil Diyan Gallan"],
      "total_plays":[7,4,5,7,8],
      "total_duration":[250,300,180,250,250]}
df=pd.DataFrame(data)
print("average plays:", df["total_plays"].mean()," songs with plays above the average can be recommended more")
print("median plays:", df["total_plays"].median()," it shows the  popularity of songs")
print("most common plays:", df["total_plays"].mode()[0],"it helps identify the most frequently appearing play count from all songs")
print("variance is:",df["total_plays"].var())
#print(df)
df

average plays: 6.2  songs with plays above the average can be recommended more
median plays: 7.0  it shows the  popularity of songs
most common plays: 7 it helps identify the most frequently appearing play count from all songs
variance is: 2.7

          song_name  total_plays  total_duration
0          Kesariya            7             250
1   Tere Sang Yaara            4             300
2         Tum Hi Ho            5             180
3     Channa Mereya            7             250
4  Dil Diyan Gallan            8             250